apiVersion: v1
kind: Service
metadata:
  name: py-app-service-external
spec:
  selector:
    app: py-app
  #specifying 'loadBalancer' makes this into an external service (somehow). Assigns an external IP address.
  #This is one way to make your application accessible externally, but to make a DNS name + support httpS - then you need an ingress.
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      #Port for the browser - has a range between 30000 and 32767
      nodePort: 30002