apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: mongo
#'Opaque' is the default type of secret for key-value pairs. Other types include TLS certificates, etc.
type: Opaque
data:
  #The values in the secret cannot be plain text- must rather be Base64 encoded - like in the example below:
  #> echo -n 'username' | base64
  #> echo -n 'password' | base64
  #Note that Base64 is a type of encoding - NOT ENCRYPTION. Anyone could decode these if they wanted to.
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=